use_frameworks!

platform :ios, '11.0'

target 'IoTMakerSdk_Example' do
  pod 'IoTMakerSdk', :path => '../'
  pod 'SDWebImage'
  pod 'ExpyTableView'
  
  target 'IoTMakerSdk_Tests' do
    inherit! :search_paths

    
  end
end
